services:
  go-app:
    container_name: go-app
    image: iman
    build:
      context: ./
      dockerfile: armaniDock
      # dockerfile: mydockfile
    #      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "host=go_db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
    # server port http.ListenAndServe(":8000", router)
      - target: 8000
    # http port
        published: 8080
        protocol: tcp
    depends_on:
      - go_db
    networks:
      - localnet

  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - target: 5432
        published: 5433
        protocol: tcp
    volumes:
      - oblbibl:/var/lib/postgresql/data
    networks:
      - localnet

volumes:
  oblbibl:
networks:
  localnet:
    driver: bridge
